# Generated by Django 3.2.9 on 2021-11-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mapdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('star_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('bpm', models.IntegerField()),
                ('length', models.CharField(max_length=4)),
                ('circle_size', models.IntegerField()),
                ('approach_rate', models.DecimalField(decimal_places=1, max_digits=2)),
                ('overall_diff', models.DecimalField(decimal_places=1, max_digits=2)),
                ('hp', models.DecimalField(decimal_places=1, max_digits=2)),
                ('mapper', models.CharField(max_length=50)),
                ('map_id', models.CharField(max_length=8)),
            ],
        ),
    ]
