# Generated by Django 3.2.9 on 2021-11-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourneyapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='map_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
